name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup CI/CD Server
        run: |
          sudo apt-get update &&
          sudo apt-get install -y awscli &&
          sudo snap install bower --classic
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --force
      - run: npm install -g firebase-tools
      - run: bower install
      - name: Run build
        run: npm run build --noninteractive
        env:
          CI: false
      - run: ./scripts/create_api_dot_js.sh
      - run: firebase login:ci --interactive
      - name: Deploy to prod
        run: |
         firebase deploy
      - run: firebase logout
