name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup CI/CD Server
        run: |
          sudo apt-get update &&
          sudo apt-get install -y awscli &&
          sudo snap install bower --classic
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --force
      - run: npm install -g firebase-tools
      - run: bower install
      - name: Run build
        run: npm run build --noninteractive
        env:
          CI: false
      - run: ./scripts/create_api_dot_js.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: firebase login:ci
    - name: Deploy to prod
      run: |
        firebase deploy
    - run: firebase logout
